# Generated by Django 5.0 on 2025-08-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.agendamento',),
        ),
    ]
