# Generated by Django 5.0 on 2025-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='0000-0000', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
